spring:
  jpa:
    show-sql: true
    

app:
  report-folder: /home/dthibau/Conseil/Adami/workspace/pocjasper/micro-service/reports/
  refresh-rate: 20000

logging:
  level:
    '[fr.adami]': debug
#    '[net.sf.jasperreports]': debug

---
spring:
  config.activate.on-profile: postgres
 
  datasource:
    url: 'jdbc:postgresql://localhost:5434/f_adami'
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update  
